### ISSUE TITLE
Компакция архивов

### ISSUE THREAD

**Issue by clamodev** [eltaline/wzd#1]
Добрый день, в первую очередь, хочу поблагодарить за прекрасную утилиту, помогла решить множество проблем.

При тестировании и разработке приложения, были выставлены не оптимальные опции для wzd, из за этого было создано много архивов, позже я увеличил лимиты, но wzd пишет новые файлы в последний созданный архив, по идее должен писать в старые, если они удовлетворяют настройкам сервера.

Как можно пересобрать архивы под новые настройки лимитов?

Не до конца понятно по компакции/дефрагментации, возможно со временем сервер сам распределит файлы между архивами?

**Comment by everanium** [comment]
Добрый день, простите я забыл настроить оповещения на почту об issues себе, поэтому так долго не отвечал.

Ну самый простой вариант пересобрать архивы это распаковать их все с --delete опцией и запаковать обратно с новыми параметрами и --delete опцией при помощи wza утилиты.

https://github.com/eltaline/wza

Файлы не перераспределяются сами, отложенная дефргаментация со временем лишь уменьшает размер архивов после перезаписей или удаления. Для перераспределения естесственно надо разархивировать и заархивировать обратно с другими настройками.

**Comment by everanium** [comment]
Закрыто
